"""Evaluate the shipped weights (read back from letter-model.bin, fp16) and write
report/metrics.json, report/metrics.md, failure images, and the metrics block of MODEL_CARD.md."""
from __future__ import annotations

import gzip
import json
from collections import Counter
from pathlib import Path

import numpy as np
import torch

from . import paths, render
from .classes import CLASSES, NULL_ID
from .export import read_bin
from .train import predict

CARD_START = "<!-- metrics:start (generated by `uv run letter-model evaluate`) -->"
CARD_END = "<!-- metrics:end -->"


def _pct(x):
    return round(100 * float(x), 2)


def classifier(net) -> dict:
    dev = torch.device("cpu")
    iso = np.load(paths.CACHE / "iso_test.npz")
    neg = np.load(paths.CACHE / "neg_test.npz")
    look = np.load(paths.CACHE / "lookalike_neg_test.npy")
    shaped = np.load(paths.CACHE / "shaped_neg_test.npy") if (paths.CACHE / "shaped_neg_test.npy").exists() \
        else np.zeros(len(look), bool)
    lp = predict(net, iso["r"], iso["s"], dev)
    pred = lp.argmax(1)
    y = iso["y"]
    src = iso["src"]
    groups = {"all held-out": np.ones(len(y), bool), "UJI writers (real, stylus)": src == "uji",
              "Omniglot drawers (real, mouse)": src == "omniglot", "font styles (synthetic)": src == "ems"}
    top1 = {k: {"top1": _pct(np.mean(pred[m] == y[m])), "n": int(m.sum())} for k, m in groups.items()}
    top1_letters_only = _pct(np.mean(lp[:, :NULL_ID].argmax(1) == y))
    conf = Counter((CLASSES[a], CLASSES[b]) for a, b in zip(y, pred) if a != b).most_common(12)
    lpn = predict(net, neg["r"], neg["s"], dev)
    pn = lpn.argmax(1) == NULL_ID
    types = neg["type"]
    fp = int(np.sum(pred == NULL_ID))  # real letters called ∅

    def pr(mask):
        tp = int(np.sum(pn & mask))
        return {"recall": _pct(tp / max(1, mask.sum())), "precision": _pct(tp / max(1, tp + fp)), "n": int(mask.sum())}

    ex = look | shaped
    null = {
        "negatives that are not letter-shaped": pr(~ex),
        "negatives, only confident lookalikes excluded": pr(~look),
        "negatives, all (the spec's four types as generated)": pr(np.ones(len(pn), bool)),
        "by type (not letter-shaped)": {t: {**pr((types == t) & ~ex), "excluded share": _pct(np.mean(ex[types == t]))}
                                        for t in sorted(set(types))},
        "real letters called ∅": _pct(np.mean(pred == NULL_ID)),
    }
    # the trade-off between the targets: move the ∅ margin and watch top-1 against ∅ recall
    frontier = []
    for d in np.arange(-2.0, 3.01, 0.25):
        pp = lp.copy()
        pp[:, NULL_ID] -= d
        pnn = lpn.copy()
        pnn[:, NULL_ID] -= d
        t1 = float(np.mean(pp.argmax(1) == y))
        nn = pnn.argmax(1) == NULL_ID
        tp = int(np.sum(nn & ~ex))
        fpp = int(np.sum(pp.argmax(1) == NULL_ID))
        frontier.append({"extraMargin": round(float(d), 2), "top1": _pct(t1), "nullRecall": _pct(tp / max(1, (~ex).sum())),
                         "nullPrecision": _pct(tp / max(1, tp + fpp))})
    return {"top1": top1, "top1LettersOnly": top1_letters_only, "confusions": conf, "null": null,
            "frontier": frontier, "positives": int(len(y)), "negatives": int(len(pn))}


def seg_images(eval_json: Path, words_jsonl: Path, out: Path, n=16, seed=1):
    ev = json.loads(eval_json.read_text())
    sess = [json.loads(line) for line in open(words_jsonl)]
    fails = [f for f in ev["failures"] if not all(f["okModel"])]
    rng = np.random.default_rng(seed)
    pick = [fails[i] for i in rng.choice(len(fails), min(n, len(fails)), replace=False)] if fails else []
    imgs = []
    for f in pick:
        w = sess[f["session"]]["words"][f["word"]]
        m = f["model"]
        bad = "".join(c if ok else c.upper() for c, ok in zip(w["text"], f["okModel"]))
        meta = w.get("meta", {})
        title = f"{bad}  [{sess[f['session']]['writerId'].split(':', 1)[1]}] {meta.get('kind', '')}" + \
            (" run-on" if meta.get("joined") else "") + (" late-dots" if meta.get("late") else "")
        imgs.append(render.render_word(w, {"letterOfStroke": m["letterOfStroke"], "splits": m["splits"]},
                                       title=title, scale=0.8, show_order=True))
    if imgs:
        render.save(render.grid(imgs, 2), out)
    return len(fails)


def classifier_images(net, out: Path):
    iso = np.load(paths.CACHE / "iso_test.npz")
    lp = predict(net, iso["r"], iso["s"], torch.device("cpu"))
    pred = lp.argmax(1)
    wrong = np.where(pred != iso["y"])[0][:48]
    imgs = [render.render_raster(iso["r"][i] / 255.0, f"{CLASSES[iso['y'][i]]}→{CLASSES[pred[i]]}", zoom=3) for i in wrong]
    if imgs:
        render.save(render.grid(imgs, 12), out)


def seg_table(ev: dict) -> list[str]:
    s = ev["summary"]
    rows = ["| Subset | letters | model | geometry | live gap rule |", "|---|---:|---:|---:|---:|"]
    names = {"all": "all", "wide": "wide spacing", "tight": "tight spacing", "touching": "touching / overlapping",
             "runOn": "run-on strokes (one stroke, two letters)", "lateDotsBars": "dots and crossbars written last",
             "uji": "UJI writers", "fonts": "font styles", "omniglot": "Omniglot drawers", "real": "real writers"}
    for k, label in names.items():
        if k in s["model"]:
            rows.append(f"| {label} | {s['model'][k]['letters']} | **{s['model'][k]['letterExact']}** | "
                        f"{s['geometry'][k]['letterExact']} | {s.get('live', {}).get(k, {}).get('letterExact', '–')} |")
    rows.append(f"| after every pen-up (finished letters) | {ev['incremental']['steps']} checks | "
                f"**{ev['incremental']['model']}** | {ev['incremental']['geometry']} | – |")
    return rows


def run(log, node, bench: bool = True):
    hdr, net = read_bin(paths.BIN)
    rep = paths.REPORT
    (rep / "failures").mkdir(parents=True, exist_ok=True)
    m: dict = {"model": {"arch": [L["op"] if L["op"] != "conv" else f"conv{L['k']}x{L['k']}/{L['stride']} {L['cin']}→{L['cout']}"
                                   + (" dw" if L["groups"] > 1 else "") for L in hdr["arch"]],
                         "weights": sum(t["length"] for t in hdr["tensors"]),
                         "bytes": paths.BIN.stat().st_size,
                         "gzipBytes": len(gzip.compress(paths.BIN.read_bytes(), 9)),
                         "trainingDataHash": hdr["trainingDataHash"],
                         "segmenter": hdr.get("segmenter", {})}}
    m["classifier"] = classifier(net)
    c = m["classifier"]
    log(f"evaluate: top-1 {c['top1']['all held-out']['top1']}% (UJI {c['top1']['UJI writers (real, stylus)']['top1']}%), "
        f"∅ P {c['null']['negatives that are not letter-shaped']['precision']}% R {c['null']['negatives that are not letter-shaped']['recall']}%")
    cache = paths.CACHE
    for name in ("words_test", "words_test_extra"):
        out = cache / f"eval_{name}.json"
        txt = node("eval-segment.ts", "--model", str(paths.BIN), "--out", str(out), str(cache / f"{name}.jsonl"),
                   *([] if name == "words_test" else ["--no-incremental"]))
        ev = json.loads(out.read_text())
        ev.pop("failures", None)
        m[f"segmentation_{name}"] = ev
        for line in txt.strip().splitlines():
            log(f"evaluate {name}: {line}")
    n_fail = seg_images(cache / "eval_words_test.json", cache / "words_test.jsonl", rep / "failures" / "segmentation-sheet.png")
    classifier_images(net, rep / "failures" / "classifier-sheet.png")
    m["segmentationFailures"] = n_fail
    if bench:
        # the collection tool end to end, from file://, on a held-out writer's words
        replay = cache / "replay_all.json"
        write_replay(replay)
        try:
            txt = node("e2e-collect.ts", str(replay), str(cache / "e2e-session.json"))
            m["collectE2E"] = txt.strip().splitlines()
            for line in m["collectE2E"]:
                log(f"collect e2e: {line}")
        except SystemExit as e:
            m["collectE2E"] = [f"FAILED: {e}"]
            log(f"collect e2e: FAILED {e}")
        out = rep / "bench-headless.json"
        txt = node("bench-browser.ts", str(out))
        m["bench"] = json.loads(out.read_text())
        for line in txt.strip().splitlines():
            log(f"bench: {line}")
    (rep / "metrics.json").write_text(json.dumps(m, indent=1, ensure_ascii=False))
    md = metrics_md(m)
    (rep / "metrics.md").write_text(md)
    card = paths.ROOT / "MODEL_CARD.md"
    if card.exists():
        t = card.read_text()
        if CARD_START in t and CARD_END in t:
            a = t.index(CARD_START) + len(CARD_START)
            b = t.index(CARD_END)
            card.write_text(t[:a] + "\n" + md + "\n" + t[b:])


def write_replay(path: Path):
    """The 18 words of tools/collect, written by one held-out UJI writer (synthetic words)."""
    from . import synth as S
    from . import words as W

    gl = S.load_pickle(paths.CACHE / "glyphs.pkl")
    bs = S.by_style([g for g in gl if g.meta["split"] == "test"])
    st = sorted(k for k in bs if k.startswith("uji"))[0]
    rng = np.random.default_rng(7)
    texts = W.sentence_words() + ["it's", "wow!", "why?"]
    out = []
    for i, t in enumerate(texts):
        style = W.sample_style(rng, ["wide", "tight", "touching"][i % 3])
        w = W.compose(t, lambda c: bs[st][c][0], rng, style, aug_strength=0.45)
        out.append({"text": t, "guides": w["guides"], "strokes": [s["points"] for s in w["strokes"]]})
    path.write_text(json.dumps(out))


def metrics_md(m: dict) -> str:
    c = m["classifier"]
    L = ["### Classifier (held-out writers and styles, shipped fp16 weights)", "",
         "| Test set | n | top-1 (31 classes, ∅ counts as wrong) |", "|---|---:|---:|"]
    for k, v in c["top1"].items():
        L.append(f"| {k} | {v['n']} | **{v['top1']}** |" if k == "all held-out" else f"| {k} | {v['n']} | {v['top1']} |")
    L.append(f"| all held-out, ∅ ignored (argmax over letters) | {c['positives']} | {c['top1LettersOnly']} |")
    nl = c["null"]
    L += ["", "| ∅ (not exactly one letter) | n | precision | recall |", "|---|---:|---:|---:|"]
    for k in ("negatives that are not letter-shaped", "negatives, only confident lookalikes excluded",
              "negatives, all (the spec's four types as generated)"):
        L.append(f"| {k} | {nl[k]['n']} | {nl[k]['precision']} | {nl[k]['recall']} |")
    for t, v in nl["by type (not letter-shaped)"].items():
        L.append(f"| &nbsp;&nbsp;{t} ({v['excluded share']}% of this type are letter-shaped) | {v['n']} | – | {v['recall']} |")
    fr = c["frontier"]
    best_r = max((f for f in fr if f["nullRecall"] >= 90), key=lambda f: f["top1"], default=None)
    best_t = max((f for f in fr if f["top1"] >= 95), key=lambda f: f["nullRecall"], default=None)
    ship = min(fr, key=lambda f: abs(f["extraMargin"]))
    L += ["", "The two targets pull against each other through the ∅ margin (letter-shaped negatives excluded):", "",
          "| Operating point | top-1 | ∅ precision | ∅ recall |", "|---|---:|---:|---:|",
          f"| shipped (margin chosen on validation) | {ship['top1']} | {ship['nullPrecision']} | {ship['nullRecall']} |"]
    L.append(f"| best top-1 with ∅ recall ≥ 90% | {best_r['top1']} | {best_r['nullPrecision']} | {best_r['nullRecall']} |"
             if best_r else "| best top-1 with ∅ recall ≥ 90% | not reachable | | |")
    L.append(f"| best ∅ recall with top-1 ≥ 95% | {best_t['top1']} | {best_t['nullPrecision']} | {best_t['nullRecall']} |"
             if best_t else "| best ∅ recall with top-1 ≥ 95% | not reachable | | |")
    L.append(f"\nReal letters called ∅: {nl['real letters called ∅']}%. Most common confusions: "
             + ", ".join(f"{a}→{b} ({n})" for (a, b), n in c["confusions"][:8]) + ".")
    L += ["", "### Segmentation (held-out synthetic words, per-letter exact match, %)", ""]
    L += seg_table(m["segmentation_words_test"])
    ex = m["segmentation_words_test_extra"]["summary"]
    L.append(f"\nSecond word list (60 other common words, incl. `' ! ?`): model {ex['model']['all']['letterExact']}%, "
             f"geometry {ex['geometry']['all']['letterExact']}%, live rule {ex.get('live', {}).get('all', {}).get('letterExact', '–')}% "
             f"({ex['model']['all']['letters']} letters).")
    mm = m["model"]
    L += ["", "### Size", "", f"{mm['weights']} weights, `letter-model.bin` {mm['bytes'] / 1024:.1f} KB, "
          f"**{mm['gzipBytes'] / 1024:.1f} KB gzipped** (budget 300 KB)."]
    if "bench" in m:
        L += ["", "### Latency (tools/bench, headless, this Mac: Apple M4 Pro)", "",
              "| Browser | per candidate p50 / p95 (ms) | per pen-up re-solve p50 / p95 (ms) | cold whole-word re-solve p50 / p95 (ms) |",
              "|---|---:|---:|---:|"]
        for k, r in m["bench"].items():
            if "perCandidateMs" not in r:
                L.append(f"| {k} | {r.get('error', 'n/a')} | | |")
                continue
            f = lambda s: f"{s['p50']:.3f} / {s['p95']:.3f}" if s["p95"] < 1 else f"{s['p50']:.2f} / {s['p95']:.2f}"
            L.append(f"| {k.replace('_', ' ')} | {f(r['perCandidateMs'])} | {f(r['penUpResolveMs'])} | {f(r['coldResolveMs'])} |")
    return "\n".join(L) + "\n"
