// Build tools/collect/lib.js and tools/bench/lib.js: one IIFE bundle (global `LM`) with the
// model weights inlined. Run after every export: `npm run build:tools`.
import { build } from "esbuild";
import { copyFileSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const bin = readFileSync(here("../../letter-model/letter-model.bin"));
const out = here("../../../tools/collect/lib.js");
await build({
  entryPoints: [here("./tools-entry.ts")],
  bundle: true,
  format: "iife",
  globalName: "LM",
  target: "es2020",
  minify: true,
  legalComments: "none",
  define: { __MODEL_B64__: JSON.stringify(bin.toString("base64")) },
  banner: { js: "/* your-own-font letter model + segmenter. Generated by packages/pipeline/scripts/build-tools.ts; do not edit. MIT. */" },
  outfile: out,
});
copyFileSync(out, here("../../../tools/bench/lib.js"));
console.log(`tools lib.js ${(statSync(out).size / 1024).toFixed(0)} KB (model ${(bin.length / 1024).toFixed(0)} KB)`);

// a small set of held-out synthetic words for the bench page
const src = here("../../letter-model/data/cache/words_test.jsonl");
try {
  const sessions = readFileSync(src, "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l));
  const words: unknown[] = [];
  let k = 0;
  // committed file: UJI (CC BY 4.0) and Omniglot (MIT) writers only, never OFL-font outlines
  const permissive = sessions.filter((s) => s.writerId.includes(":uji:") || s.writerId.includes(":omniglot:"));
  for (const s of permissive) for (const w of s.words) if (k++ % 7 === 0) words.push({ text: w.text, guides: w.guides, strokes: w.strokes.map((st: { points: number[][] }) => st.points.map((p) => [p[0], p[1]])), meta: w.meta });
  writeFileSync(here("../../../tools/bench/words.js"), `/* held-out synthetic words (generated) */\nwindow.BENCH_WORDS=${JSON.stringify(words)};\n`);
  console.log(`bench words: ${words.length}`);
} catch {
  console.log("bench words: skipped (run the letter-model pipeline first)");
}
